### ISSUE TITLE
Checklist for manuscript submission

### ISSUE THREAD

**Issue by rosemm** [arcus/DART_analysis#4]
- [x] Check section headings and order against https://journals.plos.org/ploscompbiol/s/submission-guidelines#loc-manuscript-organization
- [x] Verify author list
- [x] Read the whole stupid thing out loud
- [x] Formatting for inline stats in results section
- [x] #5
